#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=15

start_service() {
    /usr/sbin/wg-quick up /etc/wireguard/sefthy-wg.conf
    /etc/init.d/sefthy-wrt-wh start
}

stop_service() {
    /usr/sbin/wg-quick down /etc/wireguard/sefthy-wg.conf
    /etc/init.d/sefthy-wrt-wh stop
}

restart() {
    stop
    start
}