#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99
STOP=01

start_service() {
    return 0
    procd_open_instance
    procd_set_param command /opt/sefthy-wrt-config/vxlan.sh
    
    procd_set_param stdout 0
    procd_set_param stderr 0
    
    procd_close_instance
}

stop_service() {
    pid=$(pgrep -f "sefthy-vxlan")
    [ -n "$pid" ] && kill $pid
}